//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Facturacion.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos_Vendidos
    {
        public int Id_Articulo { get; set; }
        public Nullable<int> Id_Producto { get; set; }
        public string Nombre_Articulo { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> Precio_Unitario { get; set; }
        public Nullable<double> Precio_Total { get; set; }
        public Nullable<int> Id_Factura { get; set; }
    }
}
