//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Facturacion.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprobantePago
    {
        public int IdComprobantePago { get; set; }
        public int NroComprobante { get; set; }
        public int IdPedido { get; set; }
        public int IdTipoComp { get; set; }
        public string MotivoEli { get; set; }
        public string Estado { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual TipoComprobantePago TipoComprobantePago { get; set; }
    }
}
