//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Facturacion.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprobantePagoEntrada
    {
        public int IdComPagoEntradas { get; set; }
        public int NroComprobante { get; set; }
        public int IdCompra { get; set; }
        public int idTipoCompCompra { get; set; }
        public System.DateTime fecha { get; set; }
        public string Estado { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual TipoComprobanteCompra TipoComprobanteCompra { get; set; }
        public virtual TipoComprobantePago TipoComprobantePago { get; set; }
    }
}
