//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Facturacion.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public int num_fact { get; set; }
        public int IdProducto { get; set; }
        public int CantidadVenta { get; set; }
        public decimal PrecioVenta { get; set; }
        public decimal Importe { get; set; }
        public int idDetalle { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Factura Factura { get; set; }
    }
}
