//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Facturacion.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Detalles = new HashSet<Detalle>();
            this.DetalleCompras = new HashSet<DetalleCompra>();
        }
    
        public int IdProducto { get; set; }
        public string NombreProducto { get; set; }
        public decimal PCProducto { get; set; }
        public decimal PVProducto { get; set; }
        public int StockProducto { get; set; }
        public System.DateTime FechaActProducto { get; set; }
        public string MarcaProducto { get; set; }
        public string UnidMedProducto { get; set; }
        public bool EstadoProducto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle> Detalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCompra> DetalleCompras { get; set; }
    }
}
